name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - setup:
      run: sudo apt install gcc-arm-none-eabi
    - uses: actions/checkout@v2
    - configure:
      run: git submodule update --init
    - name: make
      run: make -C my-project
